services:
  app:
    image: jbalibrea-web-dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:
      CONTACT_PASSWORD: ${CONTACT_PASSWORD}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      CONTACT_TO_SEND: ${CONTACT_TO_SEND}

      PUBLIC_RECAPTCHA_KEY: ${PUBLIC_RECAPTCHA_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    volumes:
      - ./:/app
    expose:
      - "4321"
    ports:
      - "4321:4321"
