services:
  web:
    build: .
    environment:
      CONTACT_PASSWORD: ${CONTACT_PASSWORD}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      CONTACT_TO_SEND: ${CONTACT_TO_SEND}

      PUBLIC_RECAPTCHA_KEY: ${PUBLIC_RECAPTCHA_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    expose:
      - "4321"
    ports:
      - "4321:4321"
